### ISSUE TITLE
ERROR NullInjectorError: StaticInjectorError(AppModule)[GoogleChartComponent -> ScriptLoaderService]: 

### ISSUE THREAD

**Issue by najeebkhan12** [FERNman/angular-google-charts#153]
I am using angular-google-charts. It works well in development mode but when I build in production and deploy the application it gives following error.
main.26f88e784d112f269367.js:40535 ERROR NullInjectorError: StaticInjectorError(AppModule)[GoogleChartComponent -> ScriptLoaderService]: 
  StaticInjectorError(Platform: core)[GoogleChartComponent -> ScriptLoaderService]: 
    NullInjectorError: No provider for ScriptLoaderService!
    at NullInjector.get (http://localhost:4200/main.26f88e784d112f269367.js:36205:27)
    at resolveToken (http://localhost:4200/main.26f88e784d112f269367.js:50994:24)
    at tryResolveToken (http://localhost:4200/main.26f88e784d112f269367.js:50920:16)
    at StaticInjector.get (http://localhost:4200/main.26f88e784d112f269367.js:50771:20)
    at resolveToken (http://localhost:4200/main.26f88e784d112f269367.js:50994:24)
    at tryResolveToken (http://localhost:4200/main.26f88e784d112f269367.js:50920:16)
    at StaticInjector.get (http://localhost:4200/main.26f88e784d112f269367.js:50771:20)
    at resolveNgModuleDep (http://localhost:4200/main.26f88e784d112f269367.js:61798:29)
    at NgModuleRef_.get (http://localhost:4200/main.26f88e784d112f269367.js:62862:16)
    at resolveDep (http://localhost:4200/main.26f88e784d112f269367.js:63390:45)

**Comment by gis-jay** [comment]
You need to import the ScriptLoaderService in your app.module.ts file and then specify it in the providers array of your module:

`import { ScriptLoaderService } from 'angular-google-charts';`
`@NgModule({
providers:[ScriptLoaderService ]
});`

**Comment by FERNman** [comment]
@gis-jay 's approach works. Another option is to simply import the `GoogleChartModule` in you app module.

I hope this helps!

**Comment by gis-jay** [comment]
@FERNman , I actually did import the GoogleChartModule in my app module initially. Running my app via ng serve worked fine, but ng build --prod failed until I specified the ScriptLoaderService in the providers array.

**Comment by FERNman** [comment]
That's very weird. Which version of Angular are you running? AFAIK, providers registered in child modules are available in the parent module as well.

**Comment by gis-jay** [comment]
8.2.3, upgrading to 9 isn't an option for my current project.

**Comment by najeebkhan12** [comment]
> You need to import the ScriptLoaderService in your app.module.ts file and then specify it in the providers array of your module:
> 
> `import { ScriptLoaderService } from 'angular-google-charts';`
> `@NgModule({ providers:[ScriptLoaderService ] });`

Thanks this worked 👍

**Comment by leandro2m** [comment]
> You need to import the ScriptLoaderService in your app.module.ts file and then specify it in the providers array of your module:
> 
> `import { ScriptLoaderService } from 'angular-google-charts';`
> `@NgModule({ providers:[ScriptLoaderService ] });`

that works for me too
